name: Report a visual bug
description: The game has a visual or gameplay issue introduced by this patch
labels: ["visual bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Show and Tell"
      description: Optionally, let us know any further details on how to get to this screen.
      placeholder: Drag and drop to upload a screenshot showing the problem.
    validations:
      required: true

  - type: input
    id: program_version
    attributes:
      label: Patch Version
      description: Can be found in the bottom-left corner of the application.
      placeholder: 'v0.1.0'
    validations:
      required: true

  - type: dropdown
    id: ui_density
    attributes:
      label: UI Density
      options:
        - "200% / 4K / 2160p"
        - "150% / 2K / 1440p"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: install_type
    attributes:
      label: Installation Type
      options:
        - "Retail (CD/DVDs)"
        - "The Sims 2: Ultimate Collection (2014)"
        - "The Sims 2: Legacy Collection (2025)"
        - "Repack (or other automated installation)"
        - "The Sims: Life Stories"
        - "The Sims 2 Super Collection (Mac)"
    validations:
      required: true
